name = "unity-a-live-group-api"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "unity-a-live-group-db"
database_id = "433e40e2-7946-4dea-92f3-31f727424cf2"
migrations_dir = "migrations"

[vars]
MONGODB_DATABASE = "unity_a_live_group"
MONGODB_COLLECTION = "registrations"
CLOUDINARY_CLOUD_NAME = "pplcot0h"
PUBLIC_BASE_URL = "https://unity-a-live-group.vercel.app"
ALLOWED_ORIGINS = "*"
